{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example",
    "module": "UberProject-EntityService",
    "version": "0.0.1-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "UberProject-EntityService-0.0.1-SNAPSHOT-plain.jar",
          "url": "UberProject-EntityService-0.0.1-SNAPSHOT-plain.jar",
          "size": 13335,
          "sha512": "96b5c824d7f0bf9bd46f0fb8b9fca1af0782fd4101d962211914b8c6de9a9c364d50b3025879c102145f5f3e194918d8d98508570ba851e5ee84a59f98b13f4e",
          "sha256": "ccf5afffd78244f577ad5fb5b03b02dc2663f087dc87eeb7342dd405d1b55084",
          "sha1": "ace535769f725e006b47d6f365609af2528716f3",
          "md5": "5edc320783e391cedcda1ccc4316e6db"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-data-jpa"
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-core"
        },
        {
          "group": "org.flywaydb",
          "module": "flyway-mysql",
          "version": {
            "requires": "8.4.4"
          }
        },
        {
          "group": "org.springframework.boot",
          "module": "spring-boot-starter-validation",
          "version": {
            "requires": "3.2.5"
          }
        },
        {
          "group": "com.mysql",
          "module": "mysql-connector-j"
        }
      ],
      "files": [
        {
          "name": "UberProject-EntityService-0.0.1-SNAPSHOT-plain.jar",
          "url": "UberProject-EntityService-0.0.1-SNAPSHOT-plain.jar",
          "size": 13335,
          "sha512": "96b5c824d7f0bf9bd46f0fb8b9fca1af0782fd4101d962211914b8c6de9a9c364d50b3025879c102145f5f3e194918d8d98508570ba851e5ee84a59f98b13f4e",
          "sha256": "ccf5afffd78244f577ad5fb5b03b02dc2663f087dc87eeb7342dd405d1b55084",
          "sha1": "ace535769f725e006b47d6f365609af2528716f3",
          "md5": "5edc320783e391cedcda1ccc4316e6db"
        }
      ]
    }
  ]
}
